---
title: Fitting GEV parameters (ongoing work)
author: Dirceu S. Reis Jr.
html-table-processing: none
---

```{r}
#| label: Carregamento
#| echo: false
#| warning: false

library(tidyverse)
library(lubridate)
library(optimx)
library(purrr)
```

```{r}
#| label: gera-GEV-teste  
#| echo: false

# Generate annual maixmum series from a GEV distribution

# alpha <- 2.2
# csi <- 7.9
# kappa <- -0.05
# 
# set.seed(123)
# p <- runif(300,0,1)
# 
# # Generate a GEV series
# Q <- csi + alpha/kappa*(1-(-log(p))^kappa)

```

```{r}
#| label: L-MOM
#| echo: false

# Function to estimate GEV parameters based upon L-MOM

L_MOM_GEV <- function(Q){
  ordered_Q <- Q[order(Q)]
  b_0 <- mean(ordered_Q)
  Cv <- sd(ordered_Q)/b_0
  n <- length(ordered_Q)
  aux <- seq(from = 1,to = n)
  aux2 <- (aux - 1)/(n*(n-1))
  b_1 <- sum(aux2*ordered_Q)
  aux3 <- aux - 2
  aux3[aux3 < 0] <- 0 
  b_2 <- sum(aux2*aux3*ordered_Q/(n-2))

  lambda_1 <- b_0
  lambda_2 <- 2*b_1 - b_0
  lambda_3 = 6*b_2 -6*b_1 + b_0

  tao_3 <- lambda_3/lambda_2

  c <- (2*b_1 - b_0)/(3*b_2 - b_0) - log(2)/log(3)

  kappa_L <- 7.859*c + 2.9554*(c^2)
  alpha_L <- lambda_2*kappa_L/((1 - 2^(-kappa_L))*(gamma(1 + kappa_L)))
  csi_L <- lambda_1 - alpha_L/kappa_L*(1 - gamma(1 + kappa_L))

  return(c(csi_L, alpha_L, kappa_L))
}
```

```{r}
#| label: MOM_Gumbel

par_MOM_Gumbel <- function(Q){
  Q_bar <- mean(Q)
  S_Q <- sd(Q)
  
  alpha_Gumbel_MOM <- sqrt(6)*S_Q/pi
  csi_Gumbel_MOM <- Q_bar - 0.5772*S_Q/pi
  
  return(c(csi_Gumbel_MOM, alpha_Gumbel_MOM))
  
}
```


```{r}
#| label: log_Like_Gumbel

log_Like_Gumbel <- function(par,Q){
  n <- length(Q)
  csi <- par[1]
  alpha <- par[2]
  
  if (alpha<0) {
    likelihood <- 1e6
  } else {
    y <- (Q - csi)/alpha
    likelihood <- -(-n*log(alpha) - sum(y + exp(-y)))  
  }
}

```


```{r}
#| label: log_Like_GEV

# Function to estimate GEV parameters based upon Maximum Likelihood

log_Like_GEV <- function(par,Q){
  n <- length(Q)
  csi <- par[1]
  alpha <- par[2]
  kappa <- par[3]
  
  y <- 1 - kappa/alpha*(Q - csi);
  if (sum(y<0)>0) {
    term2 <- -1e6
  } else {
  term2 = (1/kappa - 1)*log(y) - y^(1/kappa)
  }
  
  if (kappa < 0) {
    if (min(Q) < csi + alpha/kappa){
      likelihood <- 1e6
      } else {
        likelihood <- -(-n*log(alpha) + sum(term2)) 
      }
    }
  if (kappa > 0) {
    if (max(Q) > csi + alpha/kappa){
      likelihood <- 1e6
    } else {
        likelihood <- -(-n*log(alpha) + sum(term2))
    }
  }
  return(likelihood)
}


```

```{r}
#| label: log_GLike_GEV

# Function to estimate GEV parameters based upon the Generalized
# Maximum Likelihood using the geophysical prior on kappa
# See Martins and Stedinger (2001)

log_GLike_GEV <- function(par,Q,meanK,varK){
  n <- length(Q)
  csi <- par[1]
  alpha <- par[2]
  kappa <- par[3]
  
  a <- 0.5
  b <- meanK + a;
  p <- b^2*(1-b)/varK - b;
  q = p*(1/b - 1);

  y <- 1 - kappa/alpha*(Q - csi);
  if (sum(y<0)>0) {
    term2 <- -1e6
  } else {
  term2 = (1/kappa - 1)*log(y) - y^(1/kappa)
  }

  if (kappa < 0) {
    if (min(Q) < csi + alpha/kappa){
      likelihood <- 1e6
    } else {
        likelihood <- -(-n*log(alpha) + sum(term2) +
                       (p - 1)*log(a + kappa) + (q - 1)*log(a - kappa)) 
    }
    }
  if (kappa > 0) {
    if (max(Q) > csi + alpha/kappa){
      likelihood <- 1e6 
    } else {
      likelihood <- -(-n*log(alpha) + sum(term2) +
                       (p - 1)*log(a + kappa) + (q - 1)*log(a - kappa))
    }
  }
  return(likelihood)
}

```

```{r}
#| Label: parameter-estimation
#| warning: true

# # Estimate GEV parameters using L-MOM estimators
# par_LMOM <- L_MOM_GEV(Q)
# 
# # Estimate Gumbel parameters using MLE
# Gumbel_MLE <- optimx(par_MOM_Gumbel(Q),log_Like_Gumbel,
#                      method=c("Nelder-Mead","BFGS"),Q=Q)
# 
# index_max_likelihood <- which.max(Gumbel_MLE$value)
# max_likelihood_MLE_Gumbel <- Gumbel_MLE$value[index_max_likelihood]
# par_MLE_Gumbel <- Gumbel_MLE[index_max_likelihood,1:2]
# 
# # Estimate GEV parameters using MLE 
# GEV_MLE <- optimx(par_LMOM,log_Like_GEV,method=c("Nelder-Mead","BFGS")
#                         ,Q=Q)
# 
# index_max_likelihood <- which.max(GEV_MLE$value)
# max_likelihood_MLE <- GEV_MLE$value[index_max_likelihood]
# par_MLE <- GEV_MLE[index_max_likelihood,1:3]
#   
# # Estimate GEV parameters using Generalized MLE (GMLE)
# GEV_GMLE <- optimx(par_LMOM,log_GLike_GEV,method=c("Nelder-Mead","BFGS")
#                         ,Q=Q,meanK = -0.10,varK = 0.122^2)
# index_max_likelihood <- which.max(GEV_GMLE$value)
# max_likelihood_GMLE <- GEV_GMLE$value[index_max_likelihood]
# par_GMLE <- GEV_GMLE[index_max_likelihood,1:3]


```


```{r}
#| label: Teste-map-coef
# Load the data
Pd <- readRDS("Pd.rds")

# Create a new column with the year of the observation right after the date
Pd <- Pd %>% mutate(Ano = year(Date), .after = Date)

Pd2 <- Pd %>%
  select(Estacao_codigo,Pdmax)

Pd_nested <- Pd2 %>% 
  group_by(Estacao_codigo) %>%
  nest()

Pd_nested <- Pd_nested %>%
  mutate(Coef_LMOM = map(data,~ L_MOM_GEV(.x$Pdmax)))

```




